org: ${env:ORG_NAME}
service: artist-api

provider:
  name: aws
  runtime: nodejs20.x
  memorySize: 1024
  timeout: 30
  iam:
    role: ${env:LAB_ROLE} 
  environment:
    TABLE_NAME: ${sls:stage}-t_artist
    GSI: ${sls:stage}-country-genre-index
    LSI: ${sls:stage}-name-index
    LAMBDA_FUNCTION_NAME: user-api-${sls:stage}-validateToken

functions:
  getAllArtistsWP:
    handler: handler/getAllArtistsWP.handler
    events:
      - http:
          path: /artist/all/{provider_id}
          method: get
          cors: true
          integration: lambda
          request:
            parameters:
              querystrings:
                limit: true
                exclusiveStartKey: true

  getArtistById:
    handler: handler/getArtistById.handler
    events:
      - http:
          path: /artist/{provider_id}/{artist_id}
          method: get
          cors: true
          integration: lambda

  #LSI
  getArtistByNameWP:
    handler: handler/getArtistByNameWP.handler
    events:
      - http:
          path: /artist/by-name/{provider_id}
          method: get
          cors: true
          integration: lambda
          request:
            parameters:
              querystrings:
                name: true
                limit: true
                exclusiveStartKey: true
  #GSI
  getArtistByCountry_Genre:
    handler: handler/getArtistByCountry_Genre.handler
    events:
      - http:
          path: /artist/by-country-genre
          method: get
          cors: true
          integration: lambda
          request:
            parameters:
              querystrings:
                country: true
                genre: true
                limit: true
                exclusiveStartKey: true

  createArtists:
    handler: handler/createArtists.handler
    events:
      - http:
          path: /artist/create
          method: post
          cors: true
          integration: lambda

  updateArtist:
    handler: handler/updateArtist.handler
    events:
      - http:
          path: /artist/update/{provider_id}/{artist_id}
          method: put
          cors: true
          integration: lambda
          
  deleteArtist:
    handler: handler/deleteArtist.handler
    events:
      - http:
          path: /artist/delete/{provider_id}/{artist_id}
          method: delete
          cors: true
          integration: lambda

resources:
  Resources:
    ArtistTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: provider_id
            AttributeType: S
          - AttributeName: artist_id
            AttributeType: N
          - AttributeName: name
            AttributeType: S
          - AttributeName: country
            AttributeType: S
          - AttributeName: genre
            AttributeType: S
        KeySchema:
          - AttributeName: provider_id
            KeyType: HASH
          - AttributeName: artist_id
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: ${self:provider.environment.GSI}
            KeySchema:
              - AttributeName: country
                KeyType: HASH
              - AttributeName: genre
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        LocalSecondaryIndexes:
          - IndexName: ${self:provider.environment.LSI}
            KeySchema:
              - AttributeName: provider_id
                KeyType: HASH
              - AttributeName: name
                KeyType: RANGE  
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
