org: ${env:ORG_NAME}
service: song-api

provider:
  name: aws
  runtime: nodejs20.x
  memorySize: 1024
  timeout: 30
  iam:
    role: ${env:LAB_ROLE}
  environment:
    TABLE_NAME: ${sls:stage}-t_song
    LSI1: ${sls:stage}-genre-index
    LSI2: ${sls:stage}-title-index 
    LAMBDA_FUNCTION_NAME: user-api-${sls:stage}-validateToken

functions:
  createSong:
    handler: handler/createSong.handler
    events:
      - http:
          path: /song/create
          method: post
          cors: true
          integration: lambda

  createSongs:
    handler: handler/createSongs.handler
    events:
      - http:
          path: /songs/create
          method: post
          cors: true
          integration: lambda

  deleteSong:
    handler: handler/deleteSong.handler
    events:
      - http:
          path: /delete/{provider_id}/{song_id}
          method: delete
          cors: true
          integration: lambda
          request:
            parameters:
              paths:
                provider_id: true
                song_id: true

  getSongById:
    handler: handler/getSongById.handler
    events:
      - http:
          path: /song/{provider_id}/{song_id}
          method: get
          cors: true
          integration: lambda
          request:
            parameters:
              paths:
                provider_id: true
                song_id: true

  getSongsByTitleWP:
    handler: handler/getSongsByTitleWP.handler
    events:
      - http:
          path: /song/by-title-wp
          method: get
          cors: true
          integration: lambda
          request:
            parameters:
              querystrings:
                title: true
                limit: true
                exclusiveStartKey: true
  getSongsByGenreWP:
    handler: handler/getSongsByGenreWP.handler
    events:
      - http:
          path: /song/by-genre-wp
          method: get
          cors: true
          integration: lambda
          request:
            parameters:
              querystrings:
                genre: true
                limit: true
                exclusiveStartKey: true

  getAllSongsWP:
    handler: handler/getAllSongsWP.handler
    events:
      - http:
          path: /song/all
          method: get
          cors: true
          integration: lambda
          request:
            parameters:
              querystrings:
                provider_id: true
                limit: true
                exclusiveStartKey: true

resources:
  Resources:
    SongsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: provider_id
            AttributeType: S
          - AttributeName: song_id
            AttributeType: N
          - AttributeName: title
            AttributeType: S
          - AttributeName: genre
            AttributeType: S
        KeySchema:
          - AttributeName: provider_id
            KeyType: HASH
          - AttributeName: song_id
            KeyType: RANGE
##TODO DEFINE GSI1 CORRECTLY 
        LocalSecondaryIndexes:
          - IndexName: ${self:provider.environment.LSI1}
            KeySchema:
              - AttributeName: provider_id
                KeyType: HASH
              - AttributeName: genre
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: ${self:provider.environment.LSI2}
            KeySchema:
              - AttributeName: provider_id
                KeyType: HASH
              - AtributeName: title
                KeyType: RANGE
            Projection:
              ProjectionType: ALL              
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
