org: ${env:ORG_NAME}
service: comment-api

provider:
  name: aws
  runtime: python3.12
  memorySize: 1024
  timeout: 30
  iam:
    role: ${env:LAB_ROLE}
  environment:
    TABLE_NAME: ${sls:stage}-t_comment
    GSI1: ${sls:stage}-user-date-index
    LSI1: ${sls:stage}-provider-post-index
    LAMBDA_FUNCTION_NAME: user-api-${sls:stage}-validateToken

functions:
  getPostComments:
    handler: get_comments_post.lambda_handler
    events:
      - http:
          path: comments/posts/{post_id}
          method: get
          cors: true
          request:
            parameters:
              paths:
                post_id: true
              querystrings:
                provider_id: true
                start_date: false
                end_date: false
                page: false
                pageSize: false
          integration: lambda

  getUserComments:
    handler: get_comments_user.lambda_handler
    events:
      - http:
          path: comments/users/{user_id}
          method: get
          cors: true
          request:
            parameters:
              paths:
                user_id: true
              querystrings:
                provider_id: true
                start_date: false
                end_date: false
                page: false
                pageSize: false
          integration: lambda

  postComment:
    handler: post_comment.lambda_handler
    events:
      - http:
          path: comments/
          method: post
          cors: true
          integration: lambda

resources:
  Resources:
    TablaComentarios:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: provider_id
            AttributeType: S
          - AttributeName: comment_id
            AttributeType: N
          - AttributeName: post_id
            AttributeType: N
          - AttributeName: date
            AttributeType: S
          - AttributeName: user_id
            AttributeType: N
        KeySchema:
          - AttributeName: provider_id
            KeyType: HASH
          - AttributeName: comment_id
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: ${self:provider.environment.GSI1}
            KeySchema:
              - AttributeName: user_id
                KeyType: HASH
              - AttributeName: date
                KeyType: RANGE
            Projection:
              ProjectionType: ALL            
        LocalSecondaryIndexes:
          - IndexName: ${self:provider.environment.LSI1}
            KeySchema:
              - AttributeName: provider_id
                KeyType: HASH
              - AttributeName: post_id
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
