org: ${env:ORG_NAME}
service: playlist-api

provider:
  name: aws
  runtime: python3.8
  memorySize: 1024
  timeout: 30
  iam:
    role: ${env:LAB_ROLE}
  environment:
    TABLE_NAME: ${sls:stage}-t_playlist
    LAMBDA_FUNCTION_NAME:  user-api-${sls:stage}-validateToken
    GSI1: ${sls:stage}-user_id-index

functions:
  createPlaylist:
    handler: createPlaylist.lambda_handler
    events:
      - http:
          path: /playlist/create
          method: post
          cors: true
          integration: lambda

  addSong:
    handler: addSong.lambda_handler
    events:
      - http:
          path: /playlist/{playlist_id}/song/{song_id}
          method: put
          cors: true
          integration: lambda

  deleteSong:
    handler: deleteSong.lambda_handler
    events:
      - http:
          path: /playlist/{playlist_id}/song/{song_id}
          method: delete
          cors: true
          integration: lambda

  getSongsPlaylist:
    handler: getSongsPlaylist.lambda_handler
    events:
      - http:
          path: /playlist/{playlist_id}/songs
          method: get
          cors: true
          integration: lambda

  deletePlaylist:
    handler: deletePlaylist.lambda_handler
    events:
      - http:
          path: /playlist/delete/{playlist_id}
          method: delete
          cors: true
          integration: lambda

resources:
  Resources:
    PlaylistsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: provider_id
            AttributeType: S
          - AttributeName: playlist_id
            AttributeType: N
          - AtributeName: user_id
            AttributeType: N
        KeySchema:
          - AttributeName: provider_id
            KeyType: HASH
          - AttributeName: playlist_id
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: ${self:provider.environment.GSI1}
            KeySchema:
              - AttributeName: user_id
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
