openapi: "3.0.1"
info:
  title: "dev-album-api"
  version: "2024-11-27T04:47:46Z"
servers:
  - url: "https://hil58kwcuk.execute-api.us-east-1.amazonaws.com/{basePath}"
    variables:
      basePath:
        default: "dev"
paths:
  /album/all/{provider_id}:
    get:
      parameters:
        - name: "provider_id"
          in: "path"
          required: true
          schema:
            type: "string"
  /album/{provider_id}/{album_id}:
    get:
      parameters:
        - name: "provider_id"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "album_id"
          in: "path"
          required: true
          schema:
            type: "string"
  /albums/create/{provider_id}:
    post:
      parameters:
        - name: "provider_id"
          in: "path"
          required: true
          schema:
            type: "string"
  /album/by-artist-release-date/{provider_id}/{artist_id}:
    get:
      parameters:
        - name: "provider_id"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "artist_id"
          in: "path"
          required: true
          schema:
            type: "string"
  /album/delete/{provider_id}/{album_id}:
    delete:
      parameters:
        - name: "provider_id"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "album_id"
          in: "path"
          required: true
          schema:
            type: "string"
  /album/create/{provider_id}:
    post:
      parameters:
        - name: "provider_id"
          in: "path"
          required: true
          schema:
            type: "string"
  /album/by-title/{provider_id}:
    get:
      parameters:
        - name: "provider_id"
          in: "path"
          required: true
          schema:
            type: "string"
components: {}
