openapi: "3.0.1"
info:
  title: "artist-api"
  version: "2024-11-27T04:48:52Z"
servers:
  - url: "https://lpyhbh0dr4.execute-api.us-east-1.amazonaws.com/{basePath}"
    variables:
      basePath:
        default: "dev"
paths:
  /artist/delete/{provider_id}/{artist_id}:
    delete:
      parameters:
        - name: "provider_id"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "artist_id"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
          content: {}
  /artist/{provider_id}/{artist_id}:
    get:
      parameters:
        - name: "provider_id"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "artist_id"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
          content: {}
  /artist/by-name/{provider_id}:
    get:
      parameters:
        - name: "provider_id"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
          content: {}
  /artist/update/{provider_id}/{artist_id}:
    put:
      parameters:
        - name: "provider_id"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "artist_id"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
          content: {}
  /artist/all/{provider_id}:
    get:
      parameters:
        - name: "provider_id"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
          content: {}
  /artist/by-country-genre/{provider_id}:
    get:
      parameters:
        - name: "provider_id"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
          content: {}
  /artist/create/{provider_id}:
    post:
      parameters:
        - name: "provider_id"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
          content: {}
components: {}
