components: {}
info:
  title: comment-api
  version: '2024-11-27T04:49:33Z'
openapi: 3.0.1
paths:
  /comment/{provider_id}/{user_id}/{post_id}:
    post:
      parameters:
      - in: path
        name: provider_id
        required: true
        schema:
          type: string
      - in: path
        name: user_id
        required: true
        schema:
          type: string
      - in: path
        name: post_id
        required: true
        schema:
          type: string
      responses:
        '200':
          content: {}
          description: 200 response
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
  /comments/post/{provider_id}/{post_id}:
    get:
      parameters:
      - in: path
        name: provider_id
        required: true
        schema:
          type: string
      - in: path
        name: post_id
        required: true
        schema:
          type: string
      responses:
        '200':
          content: {}
          description: 200 response
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
  /comments/user/{provider_id}/{user_id}:
    get:
      parameters:
      - in: path
        name: provider_id
        required: true
        schema:
          type: string
      - in: path
        name: user_id
        required: true
        schema:
          type: string
      responses:
        '200':
          content: {}
          description: 200 response
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
servers:
- url: https://vytaaq9yq0.execute-api.us-east-1.amazonaws.com/{basePath}
  variables:
    basePath:
      default: dev
