---
swagger: "2.0"
info:
  version: "2024-11-27T02:16:18Z"
  title: "dev-comment-api"
  description: "hola mundo"
host: "wrmopyy5l2.execute-api.us-east-1.amazonaws.com"
basePath: "/dev"
schemes:
- "https"
paths:
  /comments:
    post:
      consumes:
      - "application/json"
      - "application/x-www-form-urlencoded"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "400":
          description: "400 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
  /comments/posts/{post_id}:
    get:
      consumes:
      - "application/json"
      - "application/x-www-form-urlencoded"
      parameters:
      - name: "post_id"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "400":
          description: "400 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
  /comments/users/{user_id}:
    get:
      consumes:
      - "application/json"
      - "application/x-www-form-urlencoded"
      parameters:
      - name: "user_id"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "400":
          description: "400 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
