components: {}
info:
  title: playlist-api
  version: '2024-11-27T04:50:27Z'
openapi: 3.0.1
paths:
  /playlist/add-song/{provider_id}/{playlist_id}/{song_id}:
    put:
      parameters:
      - in: path
        name: provider_id
        required: true
        schema:
          type: string
      - in: path
        name: playlist_id
        required: true
        schema:
          type: string
      - in: path
        name: song_id
        required: true
        schema:
          type: string
      responses:
        '200':
          content: {}
          description: 200 response
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
  /playlist/by-user-dates/{provider_id}/{user_id}:
    get:
      parameters:
      - in: path
        name: provider_id
        required: true
        schema:
          type: string
      - in: path
        name: user_id
        required: true
        schema:
          type: string
      responses:
        '200':
          content: {}
          description: 200 response
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
  /playlist/by-user/{provider_id}/{user_id}:
    get:
      parameters:
      - in: path
        name: provider_id
        required: true
        schema:
          type: string
      - in: path
        name: user_id
        required: true
        schema:
          type: string
      responses:
        '200':
          content: {}
          description: 200 response
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
  /playlist/create/{provider_id}/{user_id}:
    post:
      parameters:
      - in: path
        name: provider_id
        required: true
        schema:
          type: string
      - in: path
        name: user_id
        required: true
        schema:
          type: string
      responses:
        '200':
          content: {}
          description: 200 response
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
  /playlist/delete-song/{provider_id}/{playlist_id}/{song_id}:
    delete:
      parameters:
      - in: path
        name: provider_id
        required: true
        schema:
          type: string
      - in: path
        name: playlist_id
        required: true
        schema:
          type: string
      - in: path
        name: song_id
        required: true
        schema:
          type: string
      responses:
        '200':
          content: {}
          description: 200 response
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
  /playlist/delete/{provider_id}/{playlist_id}:
    delete:
      parameters:
      - in: path
        name: provider_id
        required: true
        schema:
          type: string
      - in: path
        name: playlist_id
        required: true
        schema:
          type: string
      responses:
        '200':
          content: {}
          description: 200 response
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
  /playlist/songs/{provider_id}/{playlist_id}:
    get:
      parameters:
      - in: path
        name: provider_id
        required: true
        schema:
          type: string
      - in: path
        name: playlist_id
        required: true
        schema:
          type: string
      responses:
        '200':
          content: {}
          description: 200 response
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
servers:
- url: https://wy9yspwvk5.execute-api.us-east-1.amazonaws.com/{basePath}
  variables:
    basePath:
      default: dev
