components: {}
info:
  title: post-api
  version: '2024-11-27T04:51:27Z'
openapi: 3.0.1
paths:
  /post/by-user/between-created-at/{provider_id}/{user_id}:
    get:
      parameters:
      - in: path
        name: provider_id
        required: true
        schema:
          type: string
      - in: path
        name: user_id
        required: true
        schema:
          type: string
      responses:
        '200':
          content: {}
          description: 200 response
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
  /post/create/{provider_id}/{user_id}:
    post:
      parameters:
      - in: path
        name: provider_id
        required: true
        schema:
          type: string
      - in: path
        name: user_id
        required: true
        schema:
          type: string
      responses:
        '200':
          content: {}
          description: 200 response
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
  /post/delete/{provider_id}/{post_id}:
    delete:
      parameters:
      - in: path
        name: provider_id
        required: true
        schema:
          type: string
      - in: path
        name: post_id
        required: true
        schema:
          type: string
      responses:
        '200':
          content: {}
          description: 200 response
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
  /post/update/{provider_id}/{post_id}:
    put:
      parameters:
      - in: path
        name: provider_id
        required: true
        schema:
          type: string
      - in: path
        name: post_id
        required: true
        schema:
          type: string
      responses:
        '200':
          content: {}
          description: 200 response
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
  /post/{provider_id}/{post_id}:
    get:
      parameters:
      - in: path
        name: provider_id
        required: true
        schema:
          type: string
      - in: path
        name: post_id
        required: true
        schema:
          type: string
      responses:
        '200':
          content: {}
          description: 200 response
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
  /posts/by-user/{provider_id}/{user_id}:
    get:
      parameters:
      - in: path
        name: provider_id
        required: true
        schema:
          type: string
      - in: path
        name: user_id
        required: true
        schema:
          type: string
      responses:
        '200':
          content: {}
          description: 200 response
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
  /posts/{provider_id}:
    get:
      parameters:
      - in: path
        name: provider_id
        required: true
        schema:
          type: string
      responses:
        '200':
          content: {}
          description: 200 response
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
servers:
- url: https://b2gtwjio0g.execute-api.us-east-1.amazonaws.com/{basePath}
  variables:
    basePath:
      default: dev
