---
swagger: "2.0"
info:
  version: "2024-11-27T02:18:05Z"
  title: "dev-post-api"
  description: "hola mundo"
host: "cl9ck96xh5.execute-api.us-east-1.amazonaws.com"
basePath: "/dev"
schemes:
- "https"
paths:
  /post/create:
    post:
      consumes:
      - "application/json"
      - "application/x-www-form-urlencoded"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "400":
          description: "400 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
  /post/delete/{provider_id}/{post_id}:
    delete:
      consumes:
      - "application/json"
      - "application/x-www-form-urlencoded"
      parameters:
      - name: "provider_id"
        in: "path"
        required: true
        type: "string"
      - name: "post_id"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "400":
          description: "400 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
  /post/get/{provider_id}/{post_id}:
    get:
      consumes:
      - "application/json"
      - "application/x-www-form-urlencoded"
      parameters:
      - name: "provider_id"
        in: "path"
        required: true
        type: "string"
      - name: "post_id"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "400":
          description: "400 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
  /post/getall/{provider_id}:
    get:
      consumes:
      - "application/json"
      - "application/x-www-form-urlencoded"
      parameters:
      - name: "provider_id"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "400":
          description: "400 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
  /post/getbyalbum/{provider_id}/{album_id}:
    get:
      consumes:
      - "application/json"
      - "application/x-www-form-urlencoded"
      parameters:
      - name: "provider_id"
        in: "path"
        required: true
        type: "string"
      - name: "album_id"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "400":
          description: "400 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
  /post/getbysong/{provider_id}/{song_id}:
    get:
      consumes:
      - "application/json"
      - "application/x-www-form-urlencoded"
      parameters:
      - name: "provider_id"
        in: "path"
        required: true
        type: "string"
      - name: "song_id"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "400":
          description: "400 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
  /post/getbyuser/{provider_id}/{user_id}:
    get:
      consumes:
      - "application/json"
      - "application/x-www-form-urlencoded"
      parameters:
      - name: "provider_id"
        in: "path"
        required: true
        type: "string"
      - name: "user_id"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "400":
          description: "400 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
  /post/update/{provider_id}/{post_id}:
    put:
      consumes:
      - "application/json"
      - "application/x-www-form-urlencoded"
      parameters:
      - name: "provider_id"
        in: "path"
        required: true
        type: "string"
      - name: "post_id"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "400":
          description: "400 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"

