openapi: "3.0.1"
info:
  title: "song-api"
  version: "2024-12-05T04:52:26Z"
servers:
- url: "https://gx9j3sha66.execute-api.us-east-1.amazonaws.com/{basePath}"
  variables:
    basePath:
      default: "dev"
paths:
  /songs/create/{provider_id}:
    post:
      parameters:
      - name: "provider_id"
        in: "path"
        required: true
        schema:
          type: "string"
  /song/delete/{provider_id}/{song_id}:
    delete:
      parameters:
      - name: "provider_id"
        in: "path"
        required: true
        schema:
          type: "string"
      - name: "song_id"
        in: "path"
        required: true
        schema:
          type: "string"
  /song/by-genre-duration/{provider_id}:
    get:
      parameters:
      - name: "provider_id"
        in: "path"
        required: true
        schema:
          type: "string"
  /song/{provider_id}/{song_id}:
    get:
      parameters:
      - name: "provider_id"
        in: "path"
        required: true
        schema:
          type: "string"
      - name: "song_id"
        in: "path"
        required: true
        schema:
          type: "string"
  /song/all/{provider_id}:
    get:
      parameters:
      - name: "provider_id"
        in: "path"
        required: true
        schema:
          type: "string"
  /song/by-title-wp/{provider_id}:
    get:
      parameters:
      - name: "provider_id"
        in: "path"
        required: true
        schema:
          type: "string"
  /song/create/{provider_id}:
    post:
      parameters:
      - name: "provider_id"
        in: "path"
        required: true
        schema:
          type: "string"
components: {}
