components: {}
info:
  title: user-api
  version: '2024-11-27T04:53:22Z'
openapi: 3.0.1
paths:
  /user/delete/{provider_id}/{user_id}:
    delete:
      parameters:
      - in: path
        name: provider_id
        required: true
        schema:
          type: string
      - in: path
        name: user_id
        required: true
        schema:
          type: string
      responses:
        '200':
          content: {}
          description: 200 response
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
  /user/getall/{provider_id}:
    get:
      parameters:
      - in: path
        name: provider_id
        required: true
        schema:
          type: string
      responses:
        '200':
          content: {}
          description: 200 response
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
  /user/login:
    post:
      responses:
        '200':
          content: {}
          description: 200 response
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
  /user/logout:
    post:
      responses:
        '200':
          content: {}
          description: 200 response
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
  /user/register:
    post:
      responses:
        '200':
          content: {}
          description: 200 response
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
  /user/update/{provider_id}/{user_id}:
    put:
      parameters:
      - in: path
        name: provider_id
        required: true
        schema:
          type: string
      - in: path
        name: user_id
        required: true
        schema:
          type: string
      responses:
        '200':
          content: {}
          description: 200 response
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
  /user/{provider_id}/{user_id}:
    get:
      parameters:
      - in: path
        name: provider_id
        required: true
        schema:
          type: string
      - in: path
        name: user_id
        required: true
        schema:
          type: string
      responses:
        '200':
          content: {}
          description: 200 response
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
servers:
- url: https://dsw2wcyqjl.execute-api.us-east-1.amazonaws.com/{basePath}
  variables:
    basePath:
      default: dev
