org: ${env:ORG_NAME}
service: post-api

provider:
  name: aws
  runtime: nodejs20.x
  memorySize: 1024
  timeout: 30
  iam: 
    role: ${env:LAB_ROLE}
  environment:
    TABLE_NAME: ${sls:stage}-t_post
    LSI1: ${sls:stage}-album-index
    LSI2: ${sls:stage}-song-index
    LSI3: ${sls:stage}-user-index
    LAMBDA_FUNCTION_NAME: user-api-${sls:stage}-validateToken

functions:
  getPost:
    handler: Handler/getPost.handler
    events:
      - http:
          path: /post/get/{provider_id}/{post_id}
          method: get
          cors: true
          integration: lambda
          request:
            parameters:
              paths:
                provider_id: true
                post_id: true

  getAllPostsByProvider:
    handler: Handler/getAllPostByProviderId.handler
    events:
      - http:
          path: /post/getall/{provider_id}
          method: get
          cors: true
          integration: lambda
          request:
            parameters:
              paths:
                provider_id: true
              querystrings:
                page: false
                limit: false

  getPostBySongId:
    handler: Handler/getPostbySongId.handler
    events:
      - http:
          path: /post/getbysong/{provider_id}/{song_id}
          method: get
          cors: true
          integration: lambda
          request:
            parameters:
              paths:
                provider_id: true
                song_id: true
              querystrings:
                page: false
                limit: false

  getPostsByAlbumId:
    handler: Handler/getPostByAlbumId.handler
    events:
      - http:
          path: /post/getbyalbum/{provider_id}/{album_id}
          method: get
          cors: true
          integration: lambda
          request:
            parameters:
              paths:
                provider_id: true
                album_id: true
              querystrings:
                page: false
                limit: false

  getPostsByUserId:
    handler: Handler/getPostByUserId.handler
    events:
      - http:
          path: /post/getbyuser/{provider_id}/{user_id}
          method: get
          cors: true
          integration: lambda
          request:
            parameters:
              paths:
                provider_id: true
                user_id: true
              querystrings:
                page: false
                limit: false
  createPost:
    handler: Handler/createPost.handler
    events:
      - http:
          path: /post/create
          method: post
          cors: true
          integration: lambda

  updatePost:
    handler: Handler/updatePost.handler
    events:
      - http:
          path: /post/update/{provider_id}/{post_id}
          method: put
          cors: true
          integration: lambda
          request:
            parameters:
              paths:
                provider_id: true
                post_id: true

  deletePost:
    handler: Handler/deletePost.handler
    events:
      - http:
          path: /post/delete/{provider_id}/{post_id}
          method: delete
          cors: true
          integration: lambda
          request:
            parameters:
              paths:
                provider_id: true
                post_id: true


resources:
  Resources:
    PostTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: provider_id
            AttributeType: S
          - AttributeName: post_id
            AttributeType: N
          - AttributeName: song_id
            AttributeType: N
          - AttributeName: album_id
            AttributeType: N
          - AttributeName: user_id
            AttributeType: N
          - AttributeName: created_at
            AttributeType: N
        KeySchema:
          - AttributeName: provider_id
            KeyType: HASH
          - AttributeName: post_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
##TODO DEFINE GSI1 CORRECTLY
        LocalSecondaryIndexes:
            - IndexName: ${self:provider.environment.LSI1}
            KeySchema:
              - AttributeName: provider_id
                KeyType: HASH
              - AttributeName: album_id
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
           - IndexName: ${self:provider.environment.LSI2}
            KeySchema:
              - AttributeName: provider_id
                KeyType: HASH
              - AttributeName: song_id
                KeyType: RANGE
            Projection:
              ProjectionType: ALL              
          - IndexName: ${self:provider.environment.LSI3}
            KeySchema:
              - AttributeName: provider_id
                KeyType: HASH
              - AttributeName: user_id
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
