org: ${env:ORG_NAME}
service: user-api

provider:
  name: aws
  runtime: python3.8
  memorySize: 1024
  timeout: 30
  iam:
    role: ${env:LAB_ROLE}
  environment:
    TABLE_NAME: ${sls:stage}-t_user
    GSI1: ${sls:stage}-name-provider_id-index
    LSI1: ${sls:stage}-provider_id-email-index

    TABLE2_NAME: ${sls:stage}-t_token
    LSI2: ${sls:stage}-provider_id-token-index

    AUTHORIZER_FUNCTION_NAME: ${sls:stage}-validateToken

functions:
  getUser:
    handler: Handler/getUser.lambda_handler
    events:
      - http:
          path: /user/{provider_id}/{user_id} #Old /user/get/{provider_id}/{user_id}
          method: get
          cors: true
          integration: lambda
          request:
            parameters:
              paths:
                provider_id: true
                user_id: true

  getallUsersByProvider:
    handler: Handler/getallUsersByProvider.lambda_handler
    events:
      - http:
          path: /user/getall/{provider_id}
          method: get
          cors: true
          integration: lambda
          request:
            parameters:
              paths:
                provider_id: true
              querystrings:
                page: false
                limit: false

  logoutUser:
    handler: Handler/logout.lambda_handler
    events:
      - http:
          path: /user/logout
          method: post
          cors: true
          integration: lambda

  createUser:
    handler: Handler/registerUser.lambda_handler
    events:
      - http:
          path: /user/register
          method: post
          cors: true
          integration: lambda

  loginUser:
    handler: Handler/loginUser.lambda_handler
    events:
      - http:
          path: /user/login
          method: post
          cors: true
          integration: lambda

  updateUser:
    handler: Handler/updateUser.lambda_handler
    events:
      - http:
          path: /user/update/{provider_id}/{user_id}
          method: put
          cors: true
          integration: lambda
          request:
            parameters:
              paths:
                provider_id: true
                user_id: true

  deleteUser:
    handler: Handler/deleteUser.lambda_handler
    events:
      - http:
          path: /user/delete/{provider_id}/{user_id}
          method: delete
          cors: true
          integration: lambda
          request:
            parameters:
              paths:
                provider_id: true
                user_id: true

  validateToken:
    handler: Handler/validarToken.lambda_handler

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: provider_id
            AttributeType: S
          - AttributeName: user_id
            AttributeType: N
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: provider_id
            KeyType: HASH
          - AttributeName: user_id
            KeyType: RANGE
        ##TODO DEFINE GSI1 CORRECTLY
        LocalSecondaryIndexes:
          - IndexName: ${self:provider.environment.LSI1}
            KeySchema:
              - AttributeName: provider_id
                KeyType: HASH
              - AttributeName: email
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true

    TokensTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE2_NAME}
        AttributeDefinitions:
          - AttributeName: provider_id
            AttributeType: S
          - AttributeName: user_id
            AttributeType: N
          - AttributeName: token
            AttributeType: S
        KeySchema:
          - AttributeName: provider_id
            KeyType: HASH
          - AttributeName: user_id
            KeyType: RANGE
        LocalSecondaryIndexes:
          - IndexName: ${self:provider.environment.LSI2}
            KeySchema:
              - AttributeName: token
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
