org: ${env:ORG_NAME}
service: album-api

provider:
  name: aws
  runtime: nodejs20.x
  memorySize: 1024
  timeout: 30
  iam:
    role: ${env:LAB_ROLE}
  environment:
    TABLE_NAME: ${sls:stage}-t_album
    INDEX_NAME: title-index
    LAMBDA_FUNCTION_NAME:  user-api-${sls-stage}-validateToken

functions:
  createAlbum:
    handler: handler/createAlbum.handler
    events:
      - http:
          path: /album
          method: post
          cors: true
          integration: lambda

  createAlbums:
    handler: handler/createAlbums.handler
    events:
      - http:
          path: /albums
          method: post
          cors: true
          integration: lambda

  deleteAlbum:
    handler: handler/deleteAlbum.handler
    events:
      - http:
          path: /deleteAlbum/{provider_id}/{album_id}
          method: delete
          cors: true
          integration: lambda

  getAlbumById:
    handler: handler/getAlbumById.handler
    events:
      - http:
          path: /getAlbumById/{provider_id}/{album_id}
          method: get
          cors: true
          integration: lambda

  getAlbumByTitleWP:
    handler: handler/getAlbumByTitleWP.handler
    events:
      - http:
          path: /getAlbumByTitleWP
          method: get
          cors: true
          integration: lambda

  getAllAlbumsWP:
    handler: handler/getAllAlbumsWP.handler
    events:
      - http:
          path: /getAllAlbumsWP
          method: get
          cors: true
          integration: lambda

resources:
  Resources:
    AlbumsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: provider_id
            AttributeType: S
          - AttributeName: album_id
            AttributeType: N
          - AttributeName: title
            AttributeType: S
        KeySchema:
          - AttributeName: provider_id
            KeyType: HASH
          - AttributeName: album_id
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: ${self:provider.environment.INDEX_NAME}
            KeySchema:
              - AttributeName: title
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
