org: salinsuwu
service: album-api

provider:
  name: aws
  runtime: nodejs20.x
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::164273947020:role/LabRole
  environment:
    TABLE_NAME: ${sls:stage}-${env:TABLE_NAME_e}
    INDEX_NAME: ${env:INDEX_NAME_e}

functions:
  createAlbum:
    handler: handler/createAlbum.handler
    events:
      - http:
          path: /album
          method: post
          cors: true
          integration: lambda

  deleteAlbum:
    handler: handler/deleteAlbum.handler
    events:
      - http:
          path: /deleteAlbum/{provider_id}/{album_id}
          method: delete
          cors: true
          integration: lambda

  getAlbumById:
    handler: handler/getAlbumById.handler
    events:
      - http:
          path: /getAlbumById/{provider_id}/{album_id}
          method: get
          cors: true
          integration: lambda

  getAlbumByTitle:
    handler: handler/getAlbumByTitle.handler
    events:
      - http:
          path: /getAlbumByTitle
          method: get
          cors: true
          integration: lambda

  getAlbumByTitleWP:
    handler: handler/getAlbumByTitleWP.handler
    events:
      - http:
          path: /getAlbumByTitleWP
          method: get
          cors: true
          integration: lambda

  getAllAlbums:
    handler: handler/getAllAlbums.handler
    events:
      - http:
          path: /getAllAlbums
          method: get
          cors: true
          integration: lambda

  getAllAlbumsWP:
    handler: handler/getAllAlbumsWP.handler
    events:
      - http:
          path: /getAllAlbumsWP
          method: get
          cors: true
          integration: lambda

resources:
  Resources:
    SongsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: provider_id
            AttributeType: S
          - AttributeName: album_id
            AttributeType: N
          - AttributeName: title
            AttributeType: S
        KeySchema:
          - AttributeName: provider_id
            KeyType: HASH
          - AttributeName: song_id
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: ${self:provider.environment.INDEX_NAME}
            KeySchema:
              - AttributeName: title
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
