FROM python:3.8-slim

# Instalar dependencias necesarias
RUN pip install -r requirements.txt

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar el código Python al contenedor
COPY . /app

# Ejecutar el script Python
CMD ["python", "etl_process.py"]
