# Usa una imagen base de Python
FROM python:3.9-slim

# Establece el directorio de trabajo
WORKDIR /app

# Copia los archivos de la aplicación al contenedor
COPY . /app

# Actualiza pip antes de instalar las dependencias
RUN pip install --upgrade pip

# Instala las dependencias desde requirements.txt
RUN pip install -r requirements.txt

# Define el comando para ejecutar la aplicación (ajusta esto según tu archivo principal)
CMD ["python", "main.py"]
