openapi: "3.0.1"
info:
  title: "artist-api"
  version: "2024-11-28T15:10:58Z"
servers:
- url: "https://66or2ou9zl.execute-api.us-east-1.amazonaws.com/{basePath}"
  variables:
    basePath:
      default: "dev"
paths:
  /artist/{provider_id}/{artist_id}:
    get:
      parameters:
      - name: "provider_id"
        in: "path"
        required: true
        schema:
          type: "string"
      - name: "artist_id"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "Artist retrieved successfully"
  /artist/by-name:
    get:
      parameters:
      - name: "exclusiveStartKey"
        in: "query"
        schema:
          type: "string"
      - name: "limit"
        in: "query"
        schema:
          type: "string"
      - name: "provider_id"
        in: "query"
        required: true
        schema:
          type: "string"
      - name: "name"
        in: "query"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "Artist retrieved by name successfully"
  /artist/update/{artistId}:
    put:
      parameters:
      - name: "artistId"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "Artist updated successfully"
  /artist/{provider_id}/{artist_id}/delete:
    delete:
      parameters:
      - name: "provider_id"
        in: "path"
        required: true
        schema:
          type: "string"
      - name: "artist_id"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "Artist deleted successfully"
  /artist/by-genre:
    get:
      parameters:
      - name: "exclusiveStartKey"
        in: "query"
        schema:
          type: "string"
      - name: "genre"
        in: "query"
        required: true
        schema:
          type: "string"
      - name: "limit"
        in: "query"
        schema:
          type: "string"
      - name: "provider_id"
        in: "query"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "Artist retrieved by genre successfully"
  /artist/by-country:
    get:
      parameters:
      - name: "exclusiveStartKey"
        in: "query"
        schema:
          type: "string"
      - name: "limit"
        in: "query"
        schema:
          type: "string"
      - name: "provider_id"
        in: "query"
        required: true
        schema:
          type: "string"
      - name: "country"
        in: "query"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "Artist retrieved by country successfully"
  /artist/create:
    post:
      responses:
        "200":
          description: "Artist created successfully"
  /artist/all:
    get:
      parameters:
      - name: "exclusiveStartKey"
        in: "query"
        schema:
          type: "string"
      - name: "limit"
        in: "query"
        schema:
          type: "string"
      - name: "provider_id"
        in: "query"
        schema:
          type: "string"
      responses:
        "200":
          description: "All artists retrieved successfully"
components: {}
