openapi: "3.0.1"
info:
  title: "playlist-api"
  version: "2024-11-28T15:12:31Z"
servers:
- url: "https://koj47i61da.execute-api.us-east-1.amazonaws.com/{basePath}"
  variables:
    basePath:
      default: "dev"
paths:
  /playlist/user/{user_id}:
    get:
      parameters:
      - name: "user_id"
        in: "path"
        required: true
        schema:
          type: "string"
      - name: "provider_id"
        in: "query"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "Playlists retrieved successfully for the user"
  /playlist/delete/{playlist_id}:
    delete:
      parameters:
      - name: "playlist_id"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "Playlist deleted successfully"
  /playlist/create:
    post:
      parameters:
      - name: "user_id"
        in: "query"
        required: true
        schema:
          type: "string"
      - name: "playlist_id"
        in: "query"
        required: true
        schema:
          type: "string"
      - name: "provider_id"
        in: "query"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "Playlist created successfully"
  /playlist/{playlist_id}/songs:
    get:
      parameters:
      - name: "playlist_id"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "Songs retrieved successfully from the playlist"
  /playlist/{playlist_id}/song/{song_id}:
    put:
      parameters:
      - name: "playlist_id"
        in: "path"
        required: true
        schema:
          type: "string"
      - name: "song_id"
        in: "path"
        required: true
        schema:
          type: "string"
      - name: "provider_id"
        in: "query"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "Song added successfully to the playlist"
    delete:
      parameters:
      - name: "playlist_id"
        in: "path"
        required: true
        schema:
          type: "string"
      - name: "song_id"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "Song removed successfully from the playlist"
components: {}
