openapi: "3.0.1"
info:
  title: "song-api"
  version: "2024-11-28T15:14:28Z"
servers:
- url: "https://v90s2ix5l9.execute-api.us-east-1.amazonaws.com/{basePath}"
  variables:
    basePath:
      default: "dev"
paths:
  /songs:
    post:
      responses:
        "200":
          description: "Song created successfully"
  /deleteSong/{provider_id}/{song_id}:
    delete:
      parameters:
      - name: "song_id"
        in: "path"
        required: true
        schema:
          type: "string"
      - name: "provider_id"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "Song deleted successfully"
  /getAllSongsWP:
    get:
      parameters:
      - name: "exclusiveStartKey"
        in: "query"
        schema:
          type: "string"
      - name: "limit"
        in: "query"
        schema:
          type: "string"
      - name: "provider_id"
        in: "query"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "All songs retrieved successfully"
  /getSongById/{provider_id}/{song_id}:
    get:
      parameters:
      - name: "song_id"
        in: "path"
        required: true
        schema:
          type: "string"
      - name: "provider_id"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "Song retrieved successfully by ID"
  /song:
    post:
      responses:
        "200":
          description: "Song posted successfully"
  /getSongByTitleWP:
    get:
      parameters:
      - name: "exclusiveStartKey"
        in: "query"
        schema:
          type: "string"
      - name: "title"
        in: "query"
        required: true
        schema:
          type: "string"
      - name: "limit"
        in: "query"
        schema:
          type: "string"
      responses:
        "200":
          description: "Song retrieved successfully by title"
components: {}
